#!/bin/bash
#SBATCH --array=0-59
#SBATCH --nodes=1
#SBATCH --gres=gpu:4
#SBATCH --partition=batch_block1,batch_singlenode
#SBATCH --account=llmservice_fm_vision
#SBATCH --time=4:00:00

# 20 jobs x 4 hours x ~2000 samples/hour/job = ~160k samples
# 100k samples in mmpr-1.2 hard

# 60 jobs x 4 hours x ~130 samples/hour/job = ~30k samples
# 26k samples in mmpr-1.2 hard, batch 2

set -euo pipefail

WORKDIR=/lustre/fsw/portfolios/llmservice/users/jseppanen/dev/nemo-rl-n5p5-mmpr-filtered
INPUT_PATH=/lustre/fs1/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/eagle-next/image_data/rl_data/mmpr_1_2_verifiable_1120.jsonl
OUTPUT_PREFIX=$WORKDIR/mmpr_hard_qwen_output2
NUM_SHARDS=60

export HF_HOME=/lustre/fsw/portfolios/llmservice/users/jseppanen/.cache/huggingface

srun \
  --ntasks-per-node=1 \
  --nodes=$SLURM_JOB_NUM_NODES \
  --container-image=/lustre/fsw/portfolios/llmservice/users/jseppanen/sqsh/vllm-c799126-cuda-12.8.1.sqsh \
  --container-mounts=/lustre:/lustre \
  --container-workdir=$WORKDIR \
  --label \
  bash -lc "source /venv/bin/activate && python scripts/infer_mmpr_hard_qwen.py '$INPUT_PATH' \"${OUTPUT_PREFIX}_\${SLURM_ARRAY_TASK_ID}.jsonl\" --shard-id=\${SLURM_ARRAY_TASK_ID} --num-shards=${NUM_SHARDS}"
