#!/bin/bash
#SBATCH --array=0-99
#SBATCH --nodes=1
#SBATCH --gres=gpu:4
#SBATCH --partition=batch_block1,batch_singlenode
#SBATCH --account=llmservice_fm_vision
#SBATCH --time=4:00:00

# RAVEN has 42k samples
# 100 jobs x 4 hours x ~150 samples/hour/job = ~60k samples

set -euo pipefail

WORKDIR=/lustre/fsw/portfolios/llmservice/users/jseppanen/dev/nemo-rl-n5p5-mmpr-filtered
INPUT_PATH=/lustre/fsw/portfolios/llmservice/projects/llmservice_nlp_fm/datasets/eagle-next/image_data/commercial_sft_data/RAVEN/prepared/raven_train.jsonl
OUTPUT_PREFIX=$WORKDIR/raven_output
NUM_SHARDS=100

export HF_HOME=/lustre/fsw/portfolios/llmservice/users/jseppanen/.cache/huggingface

srun \
  --ntasks-per-node=1 \
  --nodes=$SLURM_JOB_NUM_NODES \
  --container-image=/lustre/fsw/portfolios/llmservice/users/jseppanen/sqsh/vllm-c799126-cuda-12.8.1.sqsh \
  --container-mounts=/lustre:/lustre \
  --container-workdir=$WORKDIR \
  --label \
  bash -lc "source /venv/bin/activate && python scripts/infer_raven.py '$INPUT_PATH' \"${OUTPUT_PREFIX}_\${SLURM_ARRAY_TASK_ID}.jsonl\" --shard-id=\${SLURM_ARRAY_TASK_ID} --num-shards=${NUM_SHARDS}"
