# Run interactively with:
# VLLM_PRECOMPILED_WHEEL_LOCATION=https://wheels.vllm.ai/855b101d75d2fc1fa02a47a6fcfa4053e8541cf0/vllm-0.13.0rc2.dev159%2Bg855b101d7-cp38-abi3-manylinux_2_31_x86_64.whl TORCH_CUDA_ARCH_LIST="9.0 10.0" NRL_FORCE_REBUILD_VENVS=true uv run examples/run_vlm_mpo.py --config examples/configs/vlm_mpo_mmpr_nanov3vl.yaml

mpo:
  max_num_epochs: 1
  max_num_steps: 7000  # ~890k samples
  val_period: 100
  val_batches: 32
  val_global_batch_size: 32
  val_micro_batch_size: 1
  val_at_start: false
  seed: 42

  reference_policy_kl_penalty: 0.05
  preference_average_log_probs: false
  sft_average_log_probs: true
  quality_average_log_probs: false
  reward_shift_momentum: 0.99
  reward_shift: 0.0

  preference_loss_weight: 0.8
  sft_loss_weight: 1.0
  bco_loss_weight: 0.2

data:
  dataset_name: "mmpr"
  data_path: "/lustre/fs1/portfolios/llmservice/users/jseppanen/data/MMPR-v1.2"
  split: "train"
  max_input_seq_length: 12000
  prompt_file: null
  system_prompt_file: "examples/prompts/nano_v3_system_prompt.txt"
  download_dir: null
  shuffle: true

policy:
  # model_name: "/lustre/fsw/portfolios/llmservice/users/kchumachenko/workspace/output/sft_moe_rl_llm_eval_mode_radio_v4_two_epochs_bs_x2_1212_matthieul/checkpoints/tp_1/check_hf_2/mcore_to_hf"
  model_name: "/lustre/fsw/portfolios/llmservice/users/jseppanen/checkpoints/nanov3vl_trunc"
  generation:
    bad_words: ["<image>", "<img>", "</img>"]
  tokenizer:
    name: ${policy.model_name}
    chat_template: "{%- set ns = namespace(enable_thinking=true, has_sys_prompt=false) -%}{%- set msg = namespace(content='') -%}{%- for message in messages -%}{%- if message['content'] is string -%}{%- if message['role'] == 'user' or message['role'] == 'system' -%}{%- if '/think' in message['content'] -%}{%- set ns.enable_thinking = true -%}{%- elif '/no_think' in message['content'] -%}{%- set ns.enable_thinking = false -%}{%- endif -%}{%- endif -%}{%- else -%}{%- for content in message['content'] -%}{%- if content['type'] == 'text' -%}{%- if message['role'] == 'user' or message['role'] == 'system' -%}{%- if '/think' in content['text'] -%}{%- set ns.enable_thinking = true -%}{%- elif '/no_think' in content['text'] -%}{%- set ns.enable_thinking = false -%}{%- endif -%}{%- endif -%}{%- endif -%}{%- endfor -%}{%- endif -%}{%- endfor -%}{%- for message in messages %}{%- if message['content'] is string -%}{%- set msg.content = message['content'] -%}{%- else -%}{%- set msg.content = '' -%}{%- for content in message['content'] -%}{%- if content['type'] == 'image' -%}{%- set msg.content = msg.content + '<image>' -%}{%- elif content['type'] == 'video' -%}{%- set msg.content = msg.content + '<video>' -%}{%- elif content['type'] == 'text' -%}{%- set msg.content = msg.content + content['text'] -%}{%- endif -%}{%- endfor -%}{%- endif -%}{%- if message['role'] == 'system' %}{{- '<SPECIAL_10>System\n' + msg.content }}{%- if tools -%}{%- if msg.content != '' -%}{{- '\n\n' -}}{%- endif -%}{{- 'You can use the following tools to assist the user if required:\n<AVAILABLE_TOOLS>[' -}}{%- for tool in tools -%}{{- (tool.function if tool.function is defined else tool) | tojson -}}{{- ', ' if not loop.last else '' -}}{%- endfor -%}{{- ']</AVAILABLE_TOOLS>\n\nIf you decide to call any tool(s), use the following format:\n<TOOLCALL>[{{\"name\": \"tool_name1\", \"arguments\": \"tool_args1\"}}, {{\"name\": \"tool_name2\", \"arguments\": \"tool_args2\"}}]</TOOLCALL>\n\nThe user will execute tool-calls and return responses from tool(s) in this format:\n<TOOL_RESPONSE>[{{\"response\": \"tool_response1\"}}, {{\"response\": \"tool_response2\"}}]</TOOL_RESPONSE>\n\nBased on the tool responses, you can call additional tools if needed, correct tool calls if any errors are found, or just respond to the user.' -}}{%- endif -%}{{- '\n' -}}{%- elif message['role'] == 'user' %}{{- '<SPECIAL_11>User\n' + msg.content + '\n' }}{%- elif message['role'] == 'tool' %}{%- if loop.first or (messages[loop.index0 - 1].role != 'tool') -%}{{- '<SPECIAL_11>User\n' + '<TOOL_RESPONSE>[' }}{%- endif -%}{{- msg.content -}}{{- ', ' if not loop.last and (messages[loop.index0 + 1].role == 'tool') else '' -}}{%- if loop.last or (messages[loop.index0 + 1].role != 'tool') -%}{{- ']</TOOL_RESPONSE>\n' -}}{%- endif -%}{%- elif message['role'] == 'assistant' %}{%- if '</think>' in msg.content %}{%- set msg.content = msg.content %}{%- endif %}{{- '<SPECIAL_11>Assistant\n' + msg.content.strip() }}{%- if message.tool_calls -%}{%- if msg.content.strip() != '' -%}{{- '\n\n' -}}{%- endif -%}{{- '<TOOLCALL>[' -}}{%- for call in message.tool_calls -%}{%- set fn = call.function if call.function is defined else call -%}{{- '{\"name\": \"' + fn.name + '\", \"arguments\": ' -}}{%- if fn.arguments is string -%}{{- fn.arguments -}}{%- else -%}{{- fn.arguments | tojson -}}{%- endif -%}{{- '}' + (', ' if not loop.last else '') -}}{%- endfor -%}{{- ']</TOOLCALL>' -}}{%- endif -%}{{- '\n<SPECIAL_12>\n' -}}{%- endif %}{%- endfor -%}{%- if add_generation_prompt %}{{- '<SPECIAL_11>Assistant\n' }}{%- if ns.enable_thinking is defined and ns.enable_thinking is false %}{{- '<think></think>' }}{%- else %}{{- '<think>\n' }}{%- endif %}{%- endif %}"
  train_global_batch_size: 128
  train_micro_batch_size: 1
  max_total_sequence_length: 12000
  precision: "bfloat16"
  offload_optimizer_for_logprob: false

  dtensor_cfg:
    enabled: false

  dynamic_batching:
    enabled: false

  sequence_packing:
    enabled: false

  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  max_grad_norm: 1.0

  optimizer: null
  scheduler: null

  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 1
    activation_checkpointing: true
    # TP=1, EP=4 → DP=2 (allows optimizer sharding on 1 node)
    # 128 experts / EP 4 = 32 experts per rank
    tensor_model_parallel_size: 1
    expert_model_parallel_size: 4
    expert_tensor_parallel_size: 1
    pipeline_model_parallel_size: 1
    context_parallel_size: 1
    pipeline_dtype: ${policy.precision}
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    sequence_parallel: false
    freeze_moe_router: false
    moe_router_dtype: "fp64"
    # MoE aux loss is currently not supported due to a known bug in Megatron-LM.
    # See https://github.com/NVIDIA/Megatron-LM/issues/1984 for more details.
    # moe_router_load_balancing_type: "aux_loss"
    moe_router_load_balancing_type: "none"
    moe_router_bias_update_rate: 1e-3
    moe_permute_fusion: false
    apply_rope_fusion: true
    bias_activation_fusion: false
    defer_fp32_logits: false
    moe_per_layer_logging: false
    radio_force_cpe_eval_mode: true

    optimizer:
      optimizer: "adam"
      lr: 5e-6
      min_lr: 2e-9
      weight_decay: 0.1
      bf16: true
      fp16: false
      params_dtype: "float32"
      adam_beta1: 0.9
      adam_beta2: 0.98
      adam_eps: 1e-8
      sgd_momentum: 0.9
      use_distributed_optimizer: true
      use_precision_aware_optimizer: true
      clip_grad: ${policy.max_grad_norm}
      optimizer_cpu_offload: true
      optimizer_offload_fraction: 1.0

    scheduler:
      start_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      end_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      weight_decay_incr_style: "constant"
      lr_decay_style: "cosine"
      lr_warmup_iters: 20
      lr_warmup_init: 2e-9

    distributed_data_parallel_config:
      grad_reduce_in_fp32: false
      overlap_grad_reduce: false
      overlap_param_gather: false
      data_parallel_sharding_strategy: "optim_grads_params"
      use_custom_fsdp: false

logger:
  log_dir: "logs"
  wandb_enabled: true
  tensorboard_enabled: false
  mlflow_enabled: false
  swanlab_enabled: false
  monitor_gpus: true
  num_val_samples_to_print: 0
  wandb:
    project: "mpo-dev-mmpr"
    name: "mpo-nano-v3-vl-mmpr"
  tensorboard:
    log_dir: "tb_logs-mpo-dev"
  mlflow:
    experiment_name: "mpo-dev"
    run_name: "mpo"
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10

cluster:
  gpus_per_node: 8
  num_nodes: 1

checkpointing:
  enabled: true
  checkpoint_dir: "results/mpo-nano-v3-vl-mmpr"
  metric_name: "val_loss"
  higher_is_better: false
  keep_top_k: 50
  save_period: 50
  checkpoint_must_save_by: "00:03:45:00"
